spring.application.name=my_silly_bestie
# Bật giao diện quản lý DB trên trình duyệt
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cấu hình kết nối (Lưu dữ liệu vào file)
spring.datasource.url=jdbc:h2:file:./data/silly_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

# Tự động khởi tạo bảng từ schema.sql và data.sql
spring.sql.init.mode=always