spring.application.name=my_silly_bestie

# Cấu hình H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/silly_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

# Tự động khởi tạo bảng từ schema.sql
spring.sql.init.mode=always

# Thêm dòng này để Hibernate (nếu có dùng) không báo lỗi
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect